name: socially
description: Launch your new project in the clearest possible way :-).

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Application version
version: 1.0.1+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.8
  # State management
  flutter_bloc: 8.1.6
  # A wrapper around InheritedWidget to make them easier to use and more reusable
  provider: 6.1.2
  # Compare objects
  equatable: 2.0.5
  # Service locator
  get_it: 7.7.0
  injectable: 2.4.4
  # Prints beautiful logs
  logger: 2.4.0
  # Functional programming in Dart
  dartz: 0.10.1
  # Shared preferences
  shared_preferences: 2.3.2
  #  Http client for Dart
  dio: 5.6.0
  # Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format
  pretty_dio_logger: 1.4.0
  # adapting screen and font size
  flutter_screenutil: 5.9.3
  # Scroll component drop-down refresh
  pull_to_refresh_flutter3: 2.0.2
  # Launching a URL in the mobile platform. Supports iOS and Android.
  url_launcher: 6.3.0
  # Simple widget wrapper to enable modal progress HUD
  modal_progress_hud_nsn: 0.5.1
  # This Flutter plugin provides an API for querying information about an application package.
  package_info_plus: 8.0.2
  # Get device information
  device_info_plus: 10.1.2
  # Show native toast
  fluttertoast: 8.2.8
  # A Flutter plugin for finding commonly used locations on the filesystem.
  # Supports iOS, Android, Linux and MacOS. Not all methods are supported on all platforms.
  path_provider: 2.1.4
  # A set of high-level APIs over PointyCastle for two-way cryptography.
  encrypt: 5.0.3
  # Flutter Modal Bottom Sheet
  modal_bottom_sheet: 3.0.0
  # Google supported fonts
  google_fonts: 6.2.1
  # To render html tag as a widget
  flutter_widget_from_html: 0.15.2
  # Code generation for immutable classes with simple syntax
  freezed_annotation: 2.4.4
  # Changing them with beautiful and easy way with animations
  animated_theme_switcher: 2.0.10
  # Global error catcher stuff
  # Sending mails
  mailer: 6.1.2
  flutter_mailer: 2.1.2
  # Provides APIs for debugging and error logging
  logging: 1.2.0
  # A crash reporting library for Dart that sends crash reports to Sentry.io.
  sentry: 8.8.0
  # Rendering lottie animations
  lottie: 3.1.2
  # A set of widgets that can be used to define a readable responsive UI for widgets
  responsive_builder: 0.7.1
  # Draw SVG files on a Flutter Widget.
  flutter_svg: 2.0.10+1
  # A flutter library to show images from the internet and keep them in the cache directory.
  cached_network_image: 3.4.0
  # A package provides an easy way to add shimmer effect in Flutter project
  shimmer: 3.0.0
  # A Flutter plugin to get the ANDROID_ID for android and identifierForVendor for iOS platforms.
  unique_identifier: 0.3.0
  # A Flutter plugin that provides a Google Maps widget.
  google_maps_flutter: 2.9.0
  # Clip your widgets with custom shapes provided.
  clippy_flutter: 2.0.0-nullsafety.1
  # plugin that decodes encoded google polyline string into list of geo-coordinates
  flutter_polyline_points: 2.1.0
  # A Flutter geolocation plugin which provides easy access to platform specific location services.
  geolocator: 12.0.0
  # Use this library to request permissions and check their status
  permission_handler: 11.3.1
  # A library to get/listen on location changes in the background
  # background_location: 0.8.1
  # A flutter package which contains a collection of some cool and awesome text animations.
  animated_text_kit: 4.2.2
  # A flutter package which will help you to generate pin code fields with beautiful design and animations.
  pin_code_fields: 8.0.1
  # Show snack bars without context
  another_flushbar: 1.12.30
  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: 3.3.0
  # A cross platform plugin for displaying local notifications.
  flutter_local_notifications: 17.2.2
  # A Flutter plugin to use the Firebase Cloud Messaging API.
  firebase_messaging: 15.0.4
  # A library for creating locks to ensure mutual exclusion when running critical sections of code.
  mutex: 3.1.0
  # A Flutter package for dynamically changing status bar color based on the background.
  statusbarz: 1.0.14
  # 🔙 Swipe to navigate back and admire beautifully morphing widgets.
  swipeable_page_route: 0.4.4
  # A Flutter plugin that allows notifications and iOS badge counts to be dismissed programmatically.
  eraser: 3.0.0
  # A Flutter plugin to share content from your Flutter app via the platform's share dialog.
  share_plus: 10.0.0
  # Flutter widget that automatically resizes text to fit perfectly within its bounds.
  auto_size_text: 3.0.0
  # A VisibilityDetector widget wraps an existing Flutter widget and fires a callback when the widget's visibility changes.
  visibility_detector: 0.4.0+2

  # Periodic callbacks in the background for both iOS and Android. Includes Android Headless implementation.
  background_fetch: 1.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  # A build system for Dart code generation and modular compilation
  build_runner: 2.4.11
  # Dependency injection code generator
  injectable_generator: 2.6.2
  # Freezed package code generator
  freezed: 2.5.2
  # Used in freezed package
  json_serializable: 6.8.0
  # For more health code
  flutter_lints: 4.0.0
  # Change native code splash
  flutter_native_splash: 2.4.1
  # Change App Package Name with single command.
  change_app_package_name: 1.3.0
  # A command-line tool which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: 0.13.1
  # Custom lints
  core_lints:
    path: ./lib/core/library/core_lints

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/png/
    - assets/images/png/error/
    - assets/images/svg/
    - assets/anim/lottie/
    - assets/anim/lottie/error/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Enable intl translation and make name of it [Translation]
flutter_intl:
  enabled: true
  class_name: S
